# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: MVCLocalPool
  demands:
  - agent.name -equals MvsAgent01


stages:
- stage: A
  displayName: 'SafetyLine1'
  variables:
  - name: ApplicationInsightsInstrumentationKey     
    value: $(ApplicationInsightsInstrumentationKey)

- stage: B
  displayName: 'SafetyLine2'
  dependsOn:
  - A

# stage C runs if B succeeds
- stage: C
  dependsOn:
  condition: succeeded('B')
  variables:
    - name: ApplicationInsightsInstrumentationKey     
      value: 'my second key'