# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: MVCLocalPool
  demands:
  - agent.name -equals MvsAgent01
  # variables:
  #   InstrumentationKeyGlobal: 'myglobalyscopedkey'


stages:
- stage: build
  displayName: 'build'
  variables:
  jobs:
  - job: A 
    steps:
    - script: 'echo Build Job'

- stage: dev1
  displayName: 'dev staging'
  dependsOn:
  - build
    variables:
  - name: InstrumentationKey
    value: 'stage A scoped key'
  jobs:
  - job: B 
    steps:
    - script: 'echo Build Dev $(InstrumentationKey)'

- stage: dev2
  displayName: 'dev'
  dependsOn:
  - build
    variables:
  - name: InstrumentationKey
    value: 'stage A scoped key'
  jobs:
  - job: C 
    steps:
    - script: 'echo Build Dev $(InstrumentationKey)'

# stage C runs if B succeeds
- stage: prod1
  displayName: 'dev stag'
  dependsOn:
  - dev2
  condition: succeeded('B')
  variables:
    - name: InstrumentationKey
      value: 'stage C scoped variable'
  jobs:
  - job: D 
    steps:
    - script: 'echo Write your commands here Job C  $(InstrumentationKey)'