# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: MVCLocalPool
  demands:
  - agent.name -equals MvsAgent01
  variables:
  - name: AIkey1
    value: 'my ai key 1'
  - name: AIkey2
    value: 'my ai key 2'
  - name: AIkey3
    value: 'my ai key 3'


stages:
- stage: A
  displayName: 'test1'
  variables:
  - name: InstrumentationKey
    value: '%AIkey1%'
  jobs:
  - job: A 
    steps:
    - script: 'echo Write your commands here Job A   %AIkey1%, $(InstrumentationKey)'

- stage: B
  displayName: 'test2'
  dependsOn:
  - A
  jobs:
  - job: B 
    steps:
    - script: 'echo Write your commands here Job B $(InstrumentationKey)'

# stage C runs if B succeeds
- stage: C
  displayName: 'test3'
  dependsOn:
  - B
  condition: succeeded('B')
  variables:
    - name: InstrumentationKey
      value: '%AIkey3%'
  jobs:
  - job: C 
    steps:
    - script: 'echo Write your commands here Job C   %AIkey3%,  $(InstrumentationKey)'