# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: MVCLocalPool
  demands:
  - agent.name -equals MvsAgent01
  variables:
    InstrumentationKeyGlobal: 'myglobalyscopedkey'


stages:
- stage: A
  displayName: 'test1'
  variables:
  - name: InstrumentationKey
    value: 'stage A scoped key'
  jobs:
  - job: A 
    steps:
    - script: 'echo Write your commands here Job A  $(InstrumentationKey)'

- stage: B
  displayName: 'test2'
  # dependsOn:
  # - A
  jobs:
  - job: B 
    steps:
    - script: 'echo Write your commands here Job B $(InstrumentationKeyGlobal)'

# stage C runs if B succeeds
- stage: C
  displayName: 'test3'
  dependsOn:
  - B
  condition: succeeded('B')
  variables:
    - name: InstrumentationKey
      value: 'stage C scoped variable'
  jobs:
  - job: C 
    steps:
    - script: 'echo Write your commands here Job C  $(InstrumentationKey)'