# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: MVCLocalPool
  demands:
  - agent.name -equals MvsAgent01
  variables:
  - name: InstrumentationKey
    value: $(ApplicationInsightsInstrumentationKey1)


stages:
- stage: A
  displayName: 'test1'
  variables:
  - name: InstrumentationKey
    value: $(ApplicationInsightsInstrumentationKey1)
  jobs:
  - job: A 
    steps:
    - script: 'echo Write your commands here Job A   $(ApplicationInsightsInstrumentationKey1), $(InstrumentationKey)'

- stage: B
  displayName: 'test2'
  dependsOn:
  - A
  jobs:
  - job: B 
    steps:
    - script: 'echo Write your commands here Job B $(InstrumentationKey)'

# stage C runs if B succeeds
- stage: C
  displayName: 'test3'
  dependsOn:
  - B
  condition: succeeded('B')
  variables:
    - name: InstrumentationKey
      value: $(ApplicationInsightsInstrumentationKey2)
  jobs:
  - job: C 
    steps:
    - script: 'echo Write your commands here Job C   $(ApplicationInsightsInstrumentationKey2),  $(InstrumentationKey)'